'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports Microsoft.VisualBasic
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Namespace DXSample.Web.SchedulerDB

	Partial Public Class Appointments
		Inherits XPLiteObject
		Private fUniqueID As Integer
		<Key(True)> _
		Public Property UniqueID() As Integer
			Get
				Return fUniqueID
			End Get
			Set(ByVal value As Integer)
				SetPropertyValue(Of Integer)("UniqueID", fUniqueID, value)
			End Set
		End Property
		Private fType As Integer
		Public Property Type() As Integer
			Get
				Return fType
			End Get
			Set(ByVal value As Integer)
				SetPropertyValue(Of Integer)("Type", fType, value)
			End Set
		End Property
		Private fStartDate As DateTime
		Public Property StartDate() As DateTime
			Get
				Return fStartDate
			End Get
			Set(ByVal value As DateTime)
				SetPropertyValue(Of DateTime)("StartDate", fStartDate, value)
			End Set
		End Property
		Private fEndDate As DateTime
		Public Property EndDate() As DateTime
			Get
				Return fEndDate
			End Get
			Set(ByVal value As DateTime)
				SetPropertyValue(Of DateTime)("EndDate", fEndDate, value)
			End Set
		End Property
		Private fAllDay As Boolean
		Public Property AllDay() As Boolean
			Get
				Return fAllDay
			End Get
			Set(ByVal value As Boolean)
				SetPropertyValue(Of Boolean)("AllDay", fAllDay, value)
			End Set
		End Property
		Private fSubject As String
		<Size(50)> _
		Public Property Subject() As String
			Get
				Return fSubject
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)("Subject", fSubject, value)
			End Set
		End Property
		Private fLocation As String
		<Size(50)> _
		Public Property Location() As String
			Get
				Return fLocation
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)("Location", fLocation, value)
			End Set
		End Property
		Private fDescription As String
		<Size(SizeAttribute.Unlimited)> _
		Public Property Description() As String
			Get
				Return fDescription
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)("Description", fDescription, value)
			End Set
		End Property
		Private fStatus As Integer
		Public Property Status() As Integer
			Get
				Return fStatus
			End Get
			Set(ByVal value As Integer)
				SetPropertyValue(Of Integer)("Status", fStatus, value)
			End Set
		End Property
		Private fLabel As Integer
		Public Property Label() As Integer
			Get
				Return fLabel
			End Get
			Set(ByVal value As Integer)
				SetPropertyValue(Of Integer)("Label", fLabel, value)
			End Set
		End Property
		Private fResourceID As Integer
		Public Property ResourceID() As Integer
			Get
				Return fResourceID
			End Get
			Set(ByVal value As Integer)
				SetPropertyValue(Of Integer)("ResourceID", fResourceID, value)
			End Set
		End Property
		Private fResourceIDs As String
		<Size(SizeAttribute.Unlimited)> _
		Public Property ResourceIDs() As String
			Get
				Return fResourceIDs
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)("ResourceIDs", fResourceIDs, value)
			End Set
		End Property
		Private fReminderInfo As String
		<Size(SizeAttribute.Unlimited)> _
		Public Property ReminderInfo() As String
			Get
				Return fReminderInfo
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)("ReminderInfo", fReminderInfo, value)
			End Set
		End Property
		Private fRecurrenceInfo As String
		<Size(SizeAttribute.Unlimited)> _
		Public Property RecurrenceInfo() As String
			Get
				Return fRecurrenceInfo
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)("RecurrenceInfo", fRecurrenceInfo, value)
			End Set
		End Property
		Private fCustomField1 As String
		<Size(SizeAttribute.Unlimited)> _
		Public Property CustomField1() As String
			Get
				Return fCustomField1
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)("CustomField1", fCustomField1, value)
			End Set
		End Property
	End Class

End Namespace
